"""
Telegram Integration Engine:
- Message sending via Telegram Bot API
- Interactive Telegram Command Poller (/watch, /watchlist, /unwatch, /price, /digest, /status, /list, /add, /remove, /report)
- Hourly Stock Price Notifier during VN stock market trading hours
"""
import logging
import os
import threading
import time
from datetime import datetime, timedelta, timezone
import requests

from . import config, db

log = logging.getLogger("telegram")

VN_TZ = timezone(timedelta(hours=7))


def send_message(text: str, chat_id: str = None) -> bool:
    target_chat = chat_id or config.TELEGRAM_CHAT_ID
    if not config.NOTIFY_TELEGRAM or not config.TELEGRAM_BOT_TOKEN or not target_chat:
        log.info("telegram disabled or missing chat_id: %s", text[:120].replace("\n", " "))
        return False
    try:
        res = requests.post(
            f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/sendMessage",
            json={"chat_id": target_chat, "text": text, "parse_mode": "HTML", "disable_web_page_preview": True},
            timeout=10,
        )
        if res.status_code != 200:
            log.warning("telegram error %s: %s", res.status_code, res.text[:200])
            return False
        return True
    except Exception as e:
        log.warning("telegram failed: %s", e)
        return False


# --- WATCHLIST MANAGEMENT (SUPABASE DB) ---

def init_watchlist_table():
    try:
        db.execute(
            """
            CREATE TABLE IF NOT EXISTS user_watchlist (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                chat_id TEXT NOT NULL,
                ticker TEXT NOT NULL,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                UNIQUE(chat_id, ticker)
            );
            """
        )
    except Exception as e:
        log.warning("init_watchlist_table note: %s", e)


def get_user_watchlist(chat_id: str) -> list:
    init_watchlist_table()
    rows = db.fetch_all("SELECT ticker FROM user_watchlist WHERE chat_id = %s ORDER BY ticker", (str(chat_id),))
    return [r["ticker"] for r in rows if "ticker" in r]


def add_to_watchlist(chat_id: str, input_str: str) -> tuple:
    init_watchlist_table()
    raw_tickers = [w.strip().upper() for w in input_str.replace(",", " ").split() if len(w.strip()) >= 2]
    if not raw_tickers:
        return False, [], []

    added = []
    for t in raw_tickers:
        if len(t) <= 6 and t.isalnum():
            db.execute(
                "INSERT INTO user_watchlist (chat_id, ticker) VALUES (%s, %s) ON CONFLICT (chat_id, ticker) DO NOTHING",
                (str(chat_id), t),
            )
            added.append(t)

    current_all = get_user_watchlist(chat_id)
    return True, added, current_all


def remove_from_watchlist(chat_id: str, input_str: str) -> tuple:
    init_watchlist_table()
    raw_tickers = [w.strip().upper() for w in input_str.replace(",", " ").split() if len(w.strip()) >= 2]
    if not raw_tickers:
        return False, [], get_user_watchlist(chat_id)

    for t in raw_tickers:
        db.execute("DELETE FROM user_watchlist WHERE chat_id = %s AND ticker = %s", (str(chat_id), t))

    current_all = get_user_watchlist(chat_id)
    return True, raw_tickers, current_all


# --- REALTIME STOCK PRICE DIGEST (VNSTOCK) ---

def fetch_price_digest(tickers: list) -> str:
    if not tickers:
        return "⚠️ Danh mục của bạn chưa có mã cổ phiếu nào."

    clean_tickers = [t.upper().strip() for t in tickers if t.strip()]
    now_str = datetime.now(VN_TZ).strftime("%H:%M %d/%m/%Y")

    try:
        import pandas as pd
        from vnstock import Trading

        t = Trading(source="vci")
        df = t.price_board(clean_tickers)
        if df is None or df.empty:
            return "⚠️ Chưa lấy được dữ liệu bảng giá chứng khoán lúc này."

        blocks = []
        for idx in range(len(df)):
            row = df.iloc[idx]

            def get_val(k1, k2=None, default=0):
                if isinstance(df.columns, pd.MultiIndex):
                    v = row.get((k1, k2))
                else:
                    v = row.get(k1) or row.get(k2)
                return v if v is not None and not pd.isna(v) else default

            tk = str(get_val("listing", "symbol", clean_tickers[min(idx, len(clean_tickers) - 1)])).upper()
            raw_match = float(get_val("match", "match_price", 0))
            raw_ref = float(get_val("match", "reference_price", get_val("listing", "ref_price", 0)))
            raw_high = float(get_val("match", "highest", 0))
            raw_low = float(get_val("match", "lowest", 0))
            raw_vol = float(get_val("match", "accumulated_volume", 0))
            raw_ceil = float(get_val("match", "ceiling_price", get_val("listing", "ceiling", 0)))
            raw_floor = float(get_val("match", "floor_price", get_val("listing", "floor", 0)))

            price = raw_match / 1000.0 if raw_match > 500 else raw_match
            ref_price = raw_ref / 1000.0 if raw_ref > 500 else raw_ref
            high = raw_high / 1000.0 if raw_high > 500 else raw_high
            low = raw_low / 1000.0 if raw_low > 500 else raw_low
            ceiling = raw_ceil / 1000.0 if raw_ceil > 500 else raw_ceil
            floor = raw_floor / 1000.0 if raw_floor > 500 else raw_floor

            change = price - ref_price if ref_price > 0 else 0.0
            change_pc = (change / ref_price * 100.0) if ref_price > 0 else 0.0

            if price >= ceiling and ceiling > 0:
                emoji = "🟣"
            elif price <= floor and floor > 0 and price > 0:
                emoji = "🔵"
            elif change > 0:
                emoji = "🟢"
            elif change < 0:
                emoji = "🔴"
            else:
                emoji = "🟡"

            sign = "+" if change > 0 else ""
            vol_str = f"{round(raw_vol / 1_000_000, 2)}M" if raw_vol >= 1_000_000 else f"{int(raw_vol):,}"

            blocks.append(
                f"{emoji} <b>{tk}</b>: <b>{price:.2f}</b> ({sign}{change:.2f} / {sign}{change_pc:.2f}%)\n"
                f"• Ref: <code>{ref_price:.2f}</code> | High: <code>{high:.2f}</code> | Low: <code>{low:.2f}</code>\n"
                f"• Khối lượng GD: <b>{vol_str} CP</b>"
            )

        return (
            f"📊 <b>BẢN TIN GIÁ CỔ PHIẾU REALTIME (WATCHLIST)</b>\n"
            f"⏰ <i>Thời điểm: {now_str} (Giờ giao dịch TTCK)</i>\n\n"
            + "\n--------------------\n".join(blocks)
            + f"\n\n🛡️ <i>Tự động cập nhật mỗi 1 tiếng trong giờ giao dịch (09:00-11:30 & 13:00-15:00).</i>"
        )
    except Exception as e:
        log.warning("fetch_price_digest error: %s", e)
        return f"⚠️ Lỗi lấy dữ liệu giá chứng khoán: {e}"


# --- HOURLY PRICE NOTIFIER LOOP ---

def is_vn_stock_market_open(dt: datetime = None) -> bool:
    if dt is None:
        dt = datetime.now(VN_TZ)
    elif dt.tzinfo is None:
        dt = dt.astimezone(VN_TZ)

    if dt.weekday() >= 5:
        return False

    tot = dt.hour * 60 + dt.minute
    in_morning = 540 <= tot <= 690  # 09:00 - 11:30
    in_afternoon = 780 <= tot <= 900  # 13:00 - 15:00
    return in_morning or in_afternoon


def hourly_stock_price_notifier_loop():
    log.info("hourly stock price notifier started")
    last_sent_hour = -1

    while True:
        try:
            now_vn = datetime.now(VN_TZ)
            curr_h = now_vn.hour

            if is_vn_stock_market_open(now_vn):
                if curr_h != last_sent_hour:
                    last_sent_hour = curr_h
                    log.info("sending hourly price updates...")
                    init_watchlist_table()
                    user_rows = db.fetch_all("SELECT DISTINCT chat_id FROM user_watchlist")
                    for u in user_rows:
                        cid = str(u["chat_id"])
                        wl = get_user_watchlist(cid)
                        if wl:
                            msg = fetch_price_digest(wl)
                            send_message(msg, chat_id=cid)
            else:
                if last_sent_hour != -1 and (curr_h < 9 or curr_h > 15 or now_vn.weekday() >= 5):
                    last_sent_hour = -1

        except Exception as e:
            log.warning("hourly_stock_price_notifier_loop error: %s", e)

        time.sleep(60)


# --- TELEGRAM INTERACTIVE COMMAND POLLER ---

def process_telegram_command(command_text: str, chat_id: str):
    text = command_text.strip()
    cid = str(chat_id)

    if text.startswith("/start") or text.startswith("/help"):
        help_msg = (
            f"🤖 <b>ĐIỀU KHIỂN TRỢ LÝ BROKER TIKTOK LIVE & DANH MỤC</b>\n\n"
            f"📌 <b>Quản Lý Danh Mục Mã Cổ Phiếu Quan Tâm:</b>\n"
            f"🔹 <code>/watch CEO, SSI, HPG</code> : Thêm mã cổ phiếu vào Watchlist\n"
            f"🔹 <code>/watchlist</code> : Xem danh sách mã đang theo dõi\n"
            f"🔹 <code>/unwatch CEO</code> : Xóa mã khỏi danh sách\n"
            f"🔹 <code>/price</code> : Xem bảng giá thị trường realtime cho Watchlist\n"
            f"🔹 <code>/digest</code> : Xem tổng hợp phân tích AI mới nhất cho Watchlist\n\n"
            f"📌 <b>Các Lệnh Giám Sát Livestream:</b>\n"
            f"🔹 <code>/status</code> : Tổng quan trạng thái Pipeline & Workers\n"
            f"🔹 <code>/list</code> : Danh sách các kênh TikTok đang theo dõi\n"
            f"🔹 <code>/add @ten_kenh</code> : Thêm kênh TikTok mới\n"
            f"🔹 <code>/remove @ten_kenh</code> : Xóa kênh TikTok\n"
            f"🔹 <code>/report</code> : Ép trích xuất báo cáo tức thì\n"
        )
        send_message(help_msg, chat_id=cid)

    elif text.startswith("/watch") or text.startswith("/addstock"):
        parts = text.split(maxsplit=1)
        if len(parts) < 2:
            send_message("⚠️ Vui lòng nhập mã cổ phiếu! Ví dụ: <code>/watch CEO, SSI, HPG</code>", chat_id=cid)
            return

        ok, added, all_wl = add_to_watchlist(cid, parts[1])
        if ok and added:
            added_str = ", ".join([f"<b>{t}</b>" for t in added])
            all_str = ", ".join([f"<code>{t}</code>" for t in all_wl])
            msg = (
                f"✅ <b>ĐÃ THÊM MÃ CỔ PHIẾU VÀO WATCHLIST!</b>\n\n"
                f"➕ Đã thêm: {added_str}\n"
                f"📋 <b>Watchlist hiện tại ({len(all_wl)} mã):</b>\n{all_str}\n\n"
                f"🛡️ <i>Dữ liệu đã được lưu an toàn xuống Supabase DB! Mỗi 1 tiếng trong giờ giao dịch hệ thống sẽ tự báo giá cho bạn!</i>"
            )
            send_message(msg, chat_id=cid)
        else:
            send_message("⚠️ Không tìm thấy mã cổ phiếu hợp lệ!", chat_id=cid)

    elif text.startswith("/watchlist") or text.startswith("/myportfolio"):
        wl = get_user_watchlist(cid)
        if not wl:
            send_message(
                "📋 <b>DANH MỤC WATCHLIST CỦA BẠN ĐANG TRỐNG</b>\n\n💡 Hãy thêm mã quan tâm: <code>/watch CEO, SSI, HPG</code>",
                chat_id=cid,
            )
            return

        w_str = "\n".join([f"• <b>{t}</b>" for t in wl])
        msg = (
            f"📋 <b>DANH MỤC {len(wl)} MÃ CỔ PHIẾU ĐANG THEO DÕI:</b>\n\n"
            f"{w_str}\n\n"
            f"💡 Thêm: <code>/watch <mã></code> | Xóa: <code>/unwatch <mã></code>\n"
            f"📊 Gõ <code>/price</code> xem giá realtime | <code>/digest</code> xem phân tích AI!"
        )
        send_message(msg, chat_id=cid)

    elif text.startswith("/unwatch") or text.startswith("/delstock"):
        parts = text.split(maxsplit=1)
        if len(parts) < 2:
            send_message("⚠️ Vui lòng nhập mã muốn xóa! Ví dụ: <code>/unwatch CEO</code>", chat_id=cid)
            return

        ok, removed, all_wl = remove_from_watchlist(cid, parts[1])
        rem_str = ", ".join([f"<b>{t}</b>" for t in removed])
        all_str = ", ".join([f"<code>{t}</code>" for t in all_wl]) if all_wl else "<i>(Trống)</i>"
        msg = f"🗑️ <b>ĐÃ XÓA MÃ CỔ PHIẾU KHỎI WATCHLIST!</b>\n\n➖ Đã xóa: {rem_str}\n📋 Danh mục còn lại: {all_str}"
        send_message(msg, chat_id=cid)

    elif text.startswith("/price") or text.startswith("/gia") or text.startswith("/banggia"):
        wl = get_user_watchlist(cid)
        if not wl:
            send_message("📋 <b>DANH MỤC WATCHLIST CỦA BẠN ĐANG TRỐNG</b>\n\n💡 Thêm mã bằng: <code>/watch CEO, SSI, HPG</code>", chat_id=cid)
            return
        send_message("⏳ Đang lấy dữ liệu bảng giá chứng khoán realtime...", chat_id=cid)
        msg = fetch_price_digest(wl)
        send_message(msg, chat_id=cid)

    elif text.startswith("/digest") or text.startswith("/summary") or text.startswith("/baocao"):
        wl = get_user_watchlist(cid)
        if not wl:
            send_message("📋 <b>DANH MỤC WATCHLIST CỦA BẠN ĐANG TRỐNG</b>", chat_id=cid)
            return
        send_message("⏳ Đang truy vấn phân tích AI mới nhất từ Supabase DB...", chat_id=cid)
        rows = db.fetch_all(
            """
            SELECT t.text, t.analysis, t.created_at, s.handle
            FROM transcripts t
            JOIN live_sessions ls ON ls.id = t.live_session_id
            JOIN sources s ON s.id = ls.source_id
            ORDER BY t.id DESC LIMIT 10
            """
        )
        if not rows:
            send_message("📊 Chưa ghi nhận kết quả phân tích AI mới trong DB.", chat_id=cid)
            return

        matched_blocks = []
        for r in rows:
            analysis_txt = r.get("analysis") or r.get("text") or ""
            handle = r.get("handle", "@broker")
            t_str = str(r.get("created_at") or "")[:16].replace("T", " ")
            matched_blocks.append(f"📌 <b>BÁO CÁO ({handle} - <code>{t_str}</code>):</b>\n{analysis_txt[:350]}...\n")

        full_msg = (
            f"📊 <b>TỔNG HỢP PHÂN TÍCH AI (WATCHLIST)</b>\n\n"
            + "\n--------------------\n".join(matched_blocks)
            + f"\n\n🛡️ <i>Dữ liệu được xử lý bởi Whisper STT & Groq Cloud LLM (GPT-OSS-120B).</i>"
        )
        send_message(full_msg, chat_id=cid)

    elif text.startswith("/status") or text.startswith("/health"):
        counts = db.fetch_one(
            """
            SELECT
              (SELECT COUNT(*) FROM sources WHERE is_active) AS active_sources,
              (SELECT COUNT(*) FROM live_sessions WHERE status = 'CAPTURING') AS capturing,
              (SELECT COUNT(*) FROM audio_chunks WHERE status = 'PENDING') AS chunks_pending,
              (SELECT COUNT(*) FROM audio_chunks WHERE status = 'PROCESSING') AS chunks_processing,
              (SELECT COUNT(*) FROM transcripts) AS transcripts_total
            """
        )
        workers = db.fetch_all("SELECT type, status, current_task FROM workers WHERE status = 'HEALTHY'")
        w_str = "\n".join([f"• <b>{w['type']}</b>: {w.get('current_task') or 'active'}" for w in workers]) if workers else "<i>(Chưa có worker nào)</i>"

        msg = (
            f"🔴 <b>TỔNG QUAN HỆ THỐNG (SELF-BROKER PIPELINE)</b>\n\n"
            f"📋 Kênh đang theo dõi: <b>{counts.get('active_sources', 0)} kênh</b>\n"
            f"🎙️ Buổi Live đang capture: <b>{counts.get('capturing', 0)} luồng</b>\n"
            f"⏳ Audio chunks đang chờ STT: <b>{counts.get('chunks_pending', 0)} chunks</b>\n"
            f"📝 Tổng số đoạn văn bản đã bóc tách: <b>{counts.get('transcripts_total', 0)} transcripts</b>\n\n"
            f"🤖 <b>Các Worker Đang Hoạt Động:</b>\n{w_str}"
        )
        send_message(msg, chat_id=cid)

    elif text.startswith("/list") or text.startswith("/channels"):
        sources = db.fetch_all("SELECT handle, is_active FROM sources ORDER BY id")
        s_str = "\n".join([f"• <code>{s['handle']}</code> ({'Active' if s['is_active'] else 'Disabled'})" for s in sources]) if sources else "<i>(Chưa có kênh nào)</i>"
        msg = f"📋 <b>DANH SÁCH {len(sources)} KÊNH TIKTOK DỰ ÁN:</b>\n\n{s_str}"
        send_message(msg, chat_id=cid)

    elif text.startswith("/add"):
        parts = text.split(maxsplit=1)
        if len(parts) < 2:
            send_message("⚠️ Vui lòng nhập tên kênh! Ví dụ: <code>/add @ten_kenh</code>", chat_id=cid)
            return
        handle = parts[1].strip()
        if not handle.startswith("@"):
            handle = f"@{handle}"
        db.execute(
            "INSERT INTO sources (platform, handle) VALUES ('tiktok', %s) ON CONFLICT (platform, handle) DO UPDATE SET is_active = TRUE",
            (handle,),
        )
        send_message(f"✅ Đã thêm kênh TikTok: <code>{handle}</code> vào danh sách giám sát!", chat_id=cid)

    elif text.startswith("/remove") or text.startswith("/del"):
        parts = text.split(maxsplit=1)
        if len(parts) < 2:
            send_message("⚠️ Vui lòng nhập tên kênh! Ví dụ: <code>/remove @ten_kenh</code>", chat_id=cid)
            return
        handle = parts[1].strip()
        if not handle.startswith("@"):
            handle = f"@{handle}"
        db.execute("UPDATE sources SET is_active = FALSE WHERE handle = %s", (handle,))
        send_message(f"🗑️ Đã ngưng giám sát kênh TikTok: <code>{handle}</code>!", chat_id=cid)

    elif text.startswith("/report"):
        send_message("⚡ Đang ép trích xuất dữ liệu Whisper STT & Phân tích AI từ audio chunk mới nhất...", chat_id=cid)
        db.execute("SELECT * FROM recover_pipeline(1, 3, 90, 30)")
        latest = db.fetch_one(
            """
            SELECT t.text, t.analysis, s.handle
            FROM transcripts t
            JOIN live_sessions ls ON ls.id = t.live_session_id
            JOIN sources s ON s.id = ls.source_id
            ORDER BY t.id DESC LIMIT 1
            """
        )
        if latest:
            send_message(
                f"📝 <b>BÁO CÁO MỚI NHẤT ({latest['handle']}):</b>\n\n{latest.get('analysis') or latest['text']}",
                chat_id=cid,
            )
        else:
            send_message("💤 Hiện tại chưa có audio chunk mới nào hoàn tất bóc tách.", chat_id=cid)


def start_telegram_command_poller():
    bot_token = config.TELEGRAM_BOT_TOKEN
    if not bot_token:
        log.info("telegram poller disabled: TELEGRAM_BOT_TOKEN missing")
        return

    log.info("telegram command poller starting...")
    last_update_id = 0

    # Start hourly stock price notifier thread alongside command poller
    t = threading.Thread(target=hourly_stock_price_notifier_loop, daemon=True)
    t.start()

    url = f"https://api.telegram.org/bot{bot_token}/getUpdates"

    while True:
        try:
            params = {"offset": last_update_id + 1, "timeout": 20}
            res = requests.get(url, params=params, timeout=25)
            if res.status_code == 200:
                data = res.json()
                if data.get("ok"):
                    for update in data.get("result", []):
                        last_update_id = update["update_id"]
                        
                        message = update.get("message") or update.get("channel_post")
                        callback_query = update.get("callback_query")

                        if callback_query:
                            cb_data = callback_query.get("data", "")
                            chat_id = str(callback_query.get("message", {}).get("chat", {}).get("id", ""))
                            if cb_data and chat_id:
                                process_telegram_command(cb_data, chat_id)
                            continue

                        if message:
                            text = message.get("text", "")
                            chat_id = str(message.get("chat", {}).get("id", ""))
                            if text and chat_id:
                                process_telegram_command(text, chat_id)

        except Exception as e:
            log.warning("telegram poller loop exception: %s", e)

        time.sleep(2)
