"""
Auto Migration Engine for Supabase PostgreSQL Database Tables
Executed automatically on server startup.
"""
import os
import urllib.parse
import psycopg2

# Auto-load .env file
env_file = os.path.join(os.path.dirname(__file__), "..", ".env")
if os.path.exists(env_file):
    with open(env_file, "r", encoding="utf-8") as f:
        for line in f:
            if "=" in line and not line.startswith("#"):
                k, v = line.strip().split("=", 1)
                os.environ[k.strip()] = v.strip()

def auto_migrate_supabase():
    url_base = os.getenv("SUPABASE_URL", "")
    db_pw = os.getenv("SUPABASE_PW", "")

    if not url_base or not db_pw:
        print("ℹ️ Bỏ qua Auto-Migration (Thiếu SUPABASE_URL hoặc SUPABASE_PW trong .env)")
        return False

    try:
        parsed = urllib.parse.urlparse(url_base)
        project_ref = parsed.netloc.split(".")[0]
    except Exception as e:
        print(f"⚠️ Không trích xuất được Project Ref từ {url_base}: {e}")
        return False

    encoded_pw = urllib.parse.quote_plus(db_pw)
    conn_str = f"postgresql://postgres:{encoded_pw}@db.{project_ref}.supabase.co:5432/postgres"

    print(f"⚡ [Auto-Migration] Đang tự động kết nối Supabase Postgres DB ({project_ref})...")

    sql_statements = """
    CREATE TABLE IF NOT EXISTS monitored_channels (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        channel_name TEXT UNIQUE NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS live_recordings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        channel TEXT NOT NULL,
        filename TEXT NOT NULL,
        audio_url TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    ALTER TABLE monitored_channels DISABLE ROW LEVEL SECURITY;
    ALTER TABLE live_recordings DISABLE ROW LEVEL SECURITY;
    """

    try:
        conn = psycopg2.connect(conn_str, connect_timeout=10)
        cur = conn.cursor()
        cur.execute(sql_statements)
        conn.commit()
        cur.close()
        conn.close()
        print("🎉 [Auto-Migration] THÀNH CÔNG! Tất cả các Table (monitored_channels, live_recordings) đã được tự động khởi tạo trên Supabase DB!")
        return True
    except Exception as e:
        print(f"⚠️ Direct 5432 note ({e}). Thử qua Pooler 6543...")
        try:
            conn_str_6543 = f"postgresql://postgres.yitqawfcjkzpsqhflwnz:{encoded_pw}@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"
            conn = psycopg2.connect(conn_str_6543, connect_timeout=10)
            cur = conn.cursor()
            cur.execute(sql_statements)
            conn.commit()
            cur.close()
            conn.close()
            print("🎉 [Auto-Migration Port 6543] THÀNH CÔNG! Đã khởi tạo Table trên Supabase DB!")
            return True
        except Exception as ex2:
            print(f"⚠️ Auto-Migration Note (Pooler 6543): {ex2}")
            return False

if __name__ == "__main__":
    auto_migrate_supabase()
