"""
Auto Migration & Table Setup Script for Supabase PostgreSQL Database
"""
import os
import psycopg2

def load_env():
    env_file = os.path.join(os.path.dirname(__file__), "..", ".env")
    if os.path.exists(env_file):
        with open(env_file, "r", encoding="utf-8") as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    k, v = line.strip().split("=", 1)
                    os.environ[k.strip()] = v.strip()

def run_migrations():
    load_env()
    
    url = os.getenv("SUPABASE_URL", "")
    pw = os.getenv("SUPABASE_PW", "")
    
    if not url or not pw:
        print("❌ Thiếu SUPABASE_URL hoặc SUPABASE_PW trong .env")
        return False
        
    # Lấy project ref từ SUPABASE_URL (ví dụ https://yitqawfcjkzpsqhflwnz.supabase.co -> yitqawfcjkzpsqhflwnz)
    ref = url.replace("https://", "").replace("http://", "").split(".")[0]
    user = f"postgres.{ref}"
    
    # Các vùng Supabase Pooler phổ biến
    poolers = [
        "aws-0-ap-southeast-2.pooler.supabase.com",
        "aws-0-ap-southeast-1.pooler.supabase.com",
        "aws-0-ap-northeast-1.pooler.supabase.com",
        "aws-0-us-east-1.pooler.supabase.com",
        "aws-0-eu-central-1.pooler.supabase.com"
    ]
    
    sql = """
    CREATE TABLE IF NOT EXISTS monitored_channels (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        channel_name TEXT UNIQUE NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS live_recordings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        channel TEXT NOT NULL,
        filename TEXT NOT NULL,
        audio_url TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

    ALTER TABLE monitored_channels DISABLE ROW LEVEL SECURITY;
    ALTER TABLE live_recordings DISABLE ROW LEVEL SECURITY;
    """

    for p in poolers:
        try:
            print(f"🔄 Đang kết nối tới Supabase Database pooler [{p}]...")
            conn = psycopg2.connect(host=p, port=5432, dbname="postgres", user=user, password=pw, connect_timeout=5)
            cur = conn.cursor()
            cur.execute(sql)
            conn.commit()
            cur.close()
            conn.close()
            print("🚀 TẠO BẢNG DATABASE TỰ ĐỘNG THÀNH CÔNG ('monitored_channels' & 'live_recordings')!")
            return True
        except Exception as e:
            continue

    print("⚠️ Không thể tự tạo bảng qua Direct Connection. Hãy dán file sql trong `supabase/migrations` vào Supabase SQL Editor.")
    return False

if __name__ == "__main__":
    run_migrations()
