"""
Supabase Database Table Setup & Auto-Creation Helper
"""
import os
import requests

env_file = os.path.join(os.path.dirname(__file__), "..", ".env")
if os.path.exists(env_file):
    with open(env_file, "r", encoding="utf-8") as f:
        for line in f:
            if "=" in line and not line.startswith("#"):
                k, v = line.strip().split("=", 1)
                os.environ[k.strip()] = v.strip()

SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")

def test_or_setup_tables():
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("❌ Chưa cấu hình SUPABASE_URL hoặc SUPABASE_KEY trong .env")
        return

    print(f"🔍 Kiểm tra kết nối Supabase DB: {SUPABASE_URL}")
    headers = {
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "apiKey": SUPABASE_KEY,
        "Content-Type": "application/json"
    }

    # Test table monitored_channels
    res = requests.get(f"{SUPABASE_URL.rstrip('/')}/rest/v1/monitored_channels?select=*", headers=headers)
    if res.status_code == 200:
        print("✅ Table 'monitored_channels' ĐÃ TỒN TẠI trên Supabase DB!")
    else:
        print(f"⚠️ Table 'monitored_channels' CHƯA TỒN TẠI trên Supabase DB (Mã lỗi {res.status_code}: {res.text})")
        print("\n👉 Vui lòng dán đoạn SQL sau vào Supabase SQL Editor để tạo Table tự động:")
        print("=" * 60)
        print("""
CREATE TABLE IF NOT EXISTS monitored_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS live_recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel TEXT NOT NULL,
    filename TEXT NOT NULL,
    audio_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE monitored_channels DISABLE ROW LEVEL SECURITY;
ALTER TABLE live_recordings DISABLE ROW LEVEL SECURITY;
        """)
        print("=" * 60)

if __name__ == "__main__":
    test_or_setup_tables()
