-- Migration Script for Supabase GitHub Integration & CLI Auto-Migrations
CREATE TABLE IF NOT EXISTS monitored_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS live_recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel TEXT NOT NULL,
    filename TEXT NOT NULL,
    audio_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE monitored_channels DISABLE ROW LEVEL SECURITY;
ALTER TABLE live_recordings DISABLE ROW LEVEL SECURITY;
