-- Self-Broker pipeline schema: DB-driven state machine (no queue).
-- Scanner / Capture / STT workers coordinate entirely through these tables.
-- Job claiming uses SELECT ... FOR UPDATE SKIP LOCKED (see claim_* functions below).

-- ============================================================
-- sources: monitored channels (replaces monitored_channels.json)
-- ============================================================
CREATE TABLE IF NOT EXISTS sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL DEFAULT 'tiktok',
    handle TEXT NOT NULL,
    display_name TEXT,
    profile_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (platform, handle)
);

-- ============================================================
-- live_sessions: one live stream of one source
-- DISCOVERED -> CAPTURING -> ENDED -> COMPLETED
--                    |            ^-(recovered: worker died)
--                    +-> FAILED
-- ============================================================
CREATE TABLE IF NOT EXISTS live_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    stream_url TEXT,
    status TEXT NOT NULL DEFAULT 'DISCOVERED'
        CHECK (status IN ('DISCOVERED', 'CAPTURING', 'ENDED', 'FINALIZING', 'COMPLETED', 'FAILED')),
    worker_id TEXT,
    chunk_count INT NOT NULL DEFAULT 0,
    error TEXT,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- only one non-completed session per source (ENDED sessions may be
-- superseded by a new one if the stream is still live, e.g. worker restart)
CREATE UNIQUE INDEX IF NOT EXISTS ux_live_sessions_active
    ON live_sessions (source_id)
    WHERE status IN ('DISCOVERED', 'CAPTURING', 'FINALIZING');

CREATE INDEX IF NOT EXISTS idx_live_sessions_status ON live_sessions (status, created_at);

-- ============================================================
-- audio_chunks: one segmented audio file per chunk
-- PENDING -> PROCESSING -> COMPLETED | FAILED
-- ============================================================
CREATE TABLE IF NOT EXISTS audio_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    live_session_id BIGINT NOT NULL REFERENCES live_sessions(id) ON DELETE CASCADE,
    sequence INT NOT NULL,
    storage_path TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    attempts INT NOT NULL DEFAULT 0,
    worker_id TEXT,
    size_bytes BIGINT,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    transcribed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (live_session_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_audio_chunks_pending ON audio_chunks (created_at) WHERE status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_audio_chunks_session ON audio_chunks (live_session_id, sequence);

-- ============================================================
-- transcripts: STT result per chunk
-- ============================================================
CREATE TABLE IF NOT EXISTS transcripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audio_chunk_id BIGINT NOT NULL UNIQUE REFERENCES audio_chunks(id) ON DELETE CASCADE,
    live_session_id BIGINT NOT NULL REFERENCES live_sessions(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    stt_model TEXT,
    language TEXT,
    analysis TEXT,
    analyzed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transcripts_session ON transcripts (live_session_id, id);

-- ============================================================
-- jobs: audit/state table (NOT a message queue)
-- ============================================================
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'RUNNING' CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    worker_id TEXT,
    attempt INT NOT NULL DEFAULT 1,
    error TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_jobs_entity ON jobs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs (status, started_at);

-- ============================================================
-- workers: heartbeat registry (dead worker detection)
-- ============================================================
CREATE TABLE IF NOT EXISTS workers (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    hostname TEXT,
    status TEXT NOT NULL DEFAULT 'HEALTHY' CHECK (status IN ('HEALTHY', 'STOPPED')),
    current_task TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_heartbeat TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Claim helpers (atomic, multi-worker safe)
-- ============================================================

-- Capture worker claims the oldest DISCOVERED session -> CAPTURING
CREATE OR REPLACE FUNCTION claim_discovered_session(p_worker_id TEXT)
RETURNS SETOF live_sessions AS $$
DECLARE
    v_session live_sessions;
BEGIN
    SELECT * INTO v_session
    FROM live_sessions
    WHERE status = 'DISCOVERED'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1;

    IF v_session.id IS NULL THEN
        RETURN;
    END IF;

    UPDATE live_sessions
    SET status = 'CAPTURING',
        worker_id = p_worker_id,
        started_at = NOW(),
        updated_at = NOW()
    WHERE id = v_session.id;

    RETURN QUERY SELECT * FROM live_sessions WHERE id = v_session.id;
END;
$$ LANGUAGE plpgsql;

-- STT worker claims the oldest PENDING chunk -> PROCESSING (attempts++)
CREATE OR REPLACE FUNCTION claim_pending_chunk(p_worker_id TEXT)
RETURNS SETOF audio_chunks AS $$
DECLARE
    v_chunk audio_chunks;
BEGIN
    SELECT * INTO v_chunk
    FROM audio_chunks
    WHERE status = 'PENDING'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1;

    IF v_chunk.id IS NULL THEN
        RETURN;
    END IF;

    UPDATE audio_chunks
    SET status = 'PROCESSING',
        worker_id = p_worker_id,
        attempts = attempts + 1,
        started_at = NOW(),
        updated_at = NOW()
    WHERE id = v_chunk.id;

    RETURN QUERY SELECT * FROM audio_chunks WHERE id = v_chunk.id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Recovery sweep (run periodically by scanner = watchdog):
--   1. stale PROCESSING chunks -> PENDING (or FAILED if out of attempts)
--   2. dead capture worker -> CAPTURING session back to DISCOVERED
--   3. abandoned DISCOVERED sessions -> FAILED
--   4. ENDED sessions with all chunks terminal -> COMPLETED
--   5. dead workers -> STOPPED
-- ============================================================
DROP FUNCTION IF EXISTS recover_pipeline(INT, INT, INT, INT);
CREATE OR REPLACE FUNCTION recover_pipeline(
    p_chunk_stale_minutes INT DEFAULT 10,
    p_max_attempts INT DEFAULT 3,
    p_worker_stale_seconds INT DEFAULT 90,
    p_discovered_timeout_minutes INT DEFAULT 30
)
RETURNS TABLE (recovered_chunks INT, failed_chunks INT, recovered_sessions INT, abandoned_sessions INT, completed_sessions INT, stopped_workers INT) AS $$
DECLARE
    v_recovered INT;
    v_failed INT;
    v_recovered_sessions INT;
    v_abandoned INT;
    v_completed INT;
    v_stopped_workers INT;
BEGIN
    -- 1a. stale PROCESSING chunks that still have attempts left
    UPDATE audio_chunks
    SET status = 'PENDING', worker_id = NULL, started_at = NULL, error = 'recovered: worker died', updated_at = NOW()
    WHERE status = 'PROCESSING'
      AND started_at < NOW() - make_interval(mins => p_chunk_stale_minutes)
      AND attempts < p_max_attempts;
    GET DIAGNOSTICS v_recovered = ROW_COUNT;

    -- 1b. stale PROCESSING chunks out of attempts
    UPDATE audio_chunks
    SET status = 'FAILED', worker_id = NULL, error = 'max attempts exceeded', updated_at = NOW()
    WHERE status = 'PROCESSING'
      AND started_at < NOW() - make_interval(mins => p_chunk_stale_minutes)
      AND attempts >= p_max_attempts;
    GET DIAGNOSTICS v_failed = ROW_COUNT;

    -- 2. capture worker heartbeat lost -> let another worker re-claim
    UPDATE live_sessions s
    SET status = 'DISCOVERED', worker_id = NULL, started_at = NULL, updated_at = NOW()
    WHERE s.status = 'CAPTURING'
      AND COALESCE(
            (SELECT w.last_heartbeat FROM workers w WHERE w.id = s.worker_id),
            s.updated_at
          ) < NOW() - make_interval(secs => p_worker_stale_seconds);
    GET DIAGNOSTICS v_recovered_sessions = ROW_COUNT;

    -- 3. nobody ever claimed these (no capture worker running / stream url expired)
    UPDATE live_sessions
    SET status = 'FAILED', error = 'abandoned: no capture worker claimed in time', ended_at = NOW(), updated_at = NOW()
    WHERE status = 'DISCOVERED'
      AND created_at < NOW() - make_interval(mins => p_discovered_timeout_minutes);
    GET DIAGNOSTICS v_abandoned = ROW_COUNT;

    -- 4. session finished when every chunk reached a terminal state
    UPDATE live_sessions s
    SET status = 'COMPLETED',
        chunk_count = (SELECT COUNT(*) FROM audio_chunks c WHERE c.live_session_id = s.id),
        completed_at = NOW(),
        updated_at = NOW()
    WHERE s.status = 'ENDED'
      AND NOT EXISTS (
            SELECT 1 FROM audio_chunks c
            WHERE c.live_session_id = s.id AND c.status IN ('PENDING', 'PROCESSING')
      );
    GET DIAGNOSTICS v_completed = ROW_COUNT;

    -- 5. mark dead workers as STOPPED (heartbeat lost for 2x worker-stale window)
    UPDATE workers
    SET status = 'STOPPED', current_task = NULL
    WHERE status = 'HEALTHY'
      AND last_heartbeat < NOW() - make_interval(secs => GREATEST(p_worker_stale_seconds * 2, 120));
    GET DIAGNOSTICS v_stopped_workers = ROW_COUNT;

    RETURN QUERY SELECT v_recovered, v_failed, v_recovered_sessions, v_abandoned, v_completed, v_stopped_workers;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Seed sources from legacy table if exists, then drop legacy tables
-- ============================================================
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'monitored_channels') THEN
        INSERT INTO sources (platform, handle, is_active)
        SELECT 'tiktok', channel_name, TRUE
        FROM monitored_channels
        ON CONFLICT (platform, handle) DO NOTHING;
        EXECUTE 'DROP TABLE IF EXISTS monitored_channels';
    END IF;
END $$;

DROP TABLE IF EXISTS live_recordings;

ALTER TABLE sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE audio_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE transcripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE workers ENABLE ROW LEVEL SECURITY;
